extra_apps/rbac/urls.py
from django.urls import path, re_path
from rbac.views import permission
app_name = 'rbac'
urlpatterns = [

    path('menu/list/', permission.menu_list, name='menu_list'), # rbac:menu_list
    path('menu/add/', permission.menu_add, name='menu_add'),
    re_path('menu/edit/(?P<pk>\d+)/', permission.menu_edit, name='menu_edit'),
    re_path('menu/del/(?P<pk>\d+)/', permission.menu_del, name='menu_del'),
    path('permission/add/', permission.permission_add, name='permission_add'),
    re_path('permission/edit/(?P<pk>\d+)/', permission.permission_edit, name='permission_edit'),
    re_path('permission/del/(?P<pk>\d+)/', permission.permission_del, name='permission_del'),

    path('multi/permissions/', permission.multi_permissions, name='multi_permissions'),

    path('distribute/permissions/', permission.distribute_permissions, name='distribute_permissions'),
    path('role/list/', permission.role_list, name='role_list'),
    re_path('role/edit/(?P<pk>\d+)/', permission.role_edit, name='role_edit'),
    re_path('role/del/(?P<pk>\d+)/', permission.role_del, name='role_del'),

]

luffy_crm/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from xstark.sites import site
from system import views as system_view
from home.views import auth, home

urlpatterns = [
    path('admin/', admin.site.urls),

    path('rbac/', include('rbac.urls', namespace='rbac')),

    path('xstark/', site.urls),
    path('xstark/login/', system_view.login),
    path('xstark/logout/', system_view.logout),
    path('xstark/profile/', system_view.profile),
    path('xstark/dashboard/', system_view.dashboard),

    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('home/', home.IndexView.as_view(), name='index'),
    path('my/', include('home.urls', namespace='home')),
]

extra_apps/rbac/models.py
from django.db import models


class Menu(models.Model):
    """
    菜单
    """
    title = models.CharField('菜单', max_length=32)
    icon = models.CharField('图标', max_length=32)

    class Meta:
        verbose_name_plural = verbose_name = '菜单管理'

    def __str__(self):
        return self.title


class Permission(models.Model):
    """
    权限表
    """
    title = models.CharField('标题', max_length=32)
    url = models.CharField('含正则的URL', max_length=128, unique=True)
    name = models.CharField('代码', max_length=64, unique=True, null=False, blank=False)
    parent = models.ForeignKey('self', verbose_name='默认选中权限', related_name='ps', null=True, blank=True,
                            help_text="对于无法作为菜单的URL，可以为其选择一个可以作为菜单的权限，那么访问时，则默认选中此权限",
                            limit_choices_to={'menu__isnull': False}, on_delete=models.SET_NULL)
    menu = models.ForeignKey(Menu, verbose_name='菜单', null=True, blank=True, help_text='null表示非菜单', on_delete=models.SET_NULL)

    class Meta:
        verbose_name_plural = verbose_name = '权限节点'

    def __str__(self):
        return self.title


class Role(models.Model):
    """
    角色
    """
    title = models.CharField('角色名称', max_length=32)
    code = models.CharField('唯一标识', max_length=16, blank=True)
    permissions = models.ManyToManyField(Permission, verbose_name='拥有的所有权限', blank=True, related_name='permissions')

    class Meta:
        verbose_name_plural = verbose_name = '角色管理'

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """
    用户表
    """
    username = models.CharField('用户名', max_length=32, null=True, blank=True)
    password = models.CharField('密码', max_length=128, null=True, blank=True)
    email = models.CharField('邮箱', max_length=32, null=True, blank=True)
    roles = models.ManyToManyField(Role, verbose_name='拥有的所有角色', blank=True)

    class Meta:
        abstract = True

extra_apps/rbac/service/routes.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls.resolvers import URLResolver
from collections import OrderedDict


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    for item in urlpatterns:
        if isinstance(item, URLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = pre_namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:
                    namespace = None
            recursion_urls(namespace, pre_url + str(item.pattern), item.url_patterns, url_ordered_dict)
        else:

            if pre_namespace:
                name = "%s:%s" % (pre_namespace, item.name,)
            else:
                name = item.name
            if not item.name:
                raise Exception('URL路由中必须设置name属性')
            url = pre_url + str(item.pattern)
            url_ordered_dict[name] = {'name': name, 'url': url}


def get_all_url_dict(ignore_namespace_list=None):
    """
    获取路由中
    :return:
    """
    ignore_list = ignore_namespace_list or []
    url_ordered_dict = OrderedDict()

    md = import_string(settings.ROOT_URLCONF)

    urlpatterns = []

    for item in md.urlpatterns:

        if not hasattr(item, 'namespace') or item.namespace in ignore_list:
            continue
        urlpatterns.append(item)

    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    return url_ordered_dict

extra_apps/rbac/views/permission.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from collections import OrderedDict
from django.shortcuts import render, HttpResponse, redirect
from django.forms import formset_factory
from django.urls import reverse

from rbac import models
from rbac.service.routes import get_all_url_dict
from rbac.forms.permission import MultiPermissionForm, RoleModelForm, MenuModelForm, PermissionModelForm


def menu_list(request):
    """
    权限管理和分配
    :param request:
    :return:
    """
    menus = models.Menu.objects.all()

    mid = request.GET.get('mid')
    root_permission_list = []
    if mid:
        # 找到可以成为菜单的权限 + 某个菜单下的
        permissions = models.Permission.objects.filter(menu_id=mid).order_by('-id')
    else:
        # 找到可以成为菜单的权限
        permissions = models.Permission.objects.filter(menu__isnull=False).order_by('-id')

    root_permission_queryset = permissions.values('id', 'title', 'url', 'name', 'menu__title')
    root_permission_dict = {}
    for item in root_permission_queryset:
        item['children'] = []
        root_permission_list.append(item)
        root_permission_dict[item['id']] = item

    # 找到可以成为菜单的权限的所有子权限
    node_permission_list = models.Permission.objects.filter(parent__in=permissions).order_by('-id').values('id',
                                                                                                        'title',
                                                                                                        'url',
                                                                                                        'name',
                                                                                                        'parent')
    for node in node_permission_list:
        parent = node['parent']
        root_permission_dict[parent]['children'].append(node)

    return render(
        request,
        'rbac/menu_list.html',
        {
            'menu_list': menus,
            'root_permission_list': root_permission_list,
            'mid': mid
        }
    )


def menu_add(request):
    """
    添加菜单
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = MenuModelForm()
    else:
        form = MenuModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('rbac:menu_list'))
    return render(request, 'rbac/menu_change.html', {'form': form})


def menu_edit(request, pk):
    """
    编辑菜单
    :param request:
    :return:
    """
    obj = models.Menu.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('菜单不存在')

    if request.method == 'GET':
        form = MenuModelForm(instance=obj)
        return render(request, 'rbac/menu_change.html', {'form': form})

    form = MenuModelForm(request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:menu_list'))


def menu_del(request, pk):
    """
    删除菜单
    :param request:
    :param pk:
    :return:
    """
    models.Menu.objects.filter(id=pk).delete()
    return redirect(reverse('rbac:menu_list'))


def permission_add(request):
    """
    添加权限
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = PermissionModelForm()
    else:
        form = PermissionModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('rbac:menu_list'))
    return render(request, 'rbac/permission_change.html', {'form': form})


def permission_edit(request, pk):
    """
    编辑权限
    :param request:
    :return:
    """
    obj = models.Permission.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('权限不存在')

    if request.method == 'GET':
        form = PermissionModelForm(instance=obj)
    else:
        form = PermissionModelForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('rbac:menu_list'))
    return render(request, 'rbac/permission_change.html', {'form': form})


def permission_del(request, pk):
    """
    删除权限
    :param request:
    :return:
    """
    models.Permission.objects.filter(id=pk).delete()
    return redirect(request.META['HTTP_REFERER'])


def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """
    post_type = request.GET.get('type')

    MultiPermissionFormSet = formset_factory(MultiPermissionForm, extra=0)
    generate_formset = None
    update_formset = None

    if request.method == 'POST' and post_type == 'generate':
        formset = MultiPermissionFormSet(request.POST)
        if not formset.is_valid():
            generate_formset = formset
        else:
            for row_dict in formset.cleaned_data:
                row_dict.pop('id')
                models.Permission.objects.create(**row_dict)

    if request.method == 'POST' and post_type == 'update':
        formset = MultiPermissionFormSet(request.POST)
        if formset.is_valid():
            for row_dict in formset.cleaned_data:
                permission_id = row_dict.pop('id')
                models.Permission.objects.filter(id=permission_id).update(**row_dict)
        else:
            update_formset = formset

    # 1.1 去数据库中获取所有权限
    # [{},{}]
    permissions = models.Permission.objects.all().values('id', 'title', 'url', 'name', 'menu_id', 'parent_id')
    # {'rbac:menu_list':{},'rbac:menu_add':{..}}
    permisssion_dict = OrderedDict()
    for per in permissions:
        permisssion_dict[per['name']] = per

    # 1.2 数据库中有的所有权限name的集合
    permission_name_set = set(permisssion_dict.keys())


    # 2.1 获取路由系统中所有的URL
    # {'rbac:menu_list':{'url':.... },,,}
    router_dict = get_all_url_dict(ignore_namespace_list=['admin'])
    print(router_dict)
    for row in permissions:
        name = row['name']
        if name in router_dict:
            router_dict[name].update(row)

    # 2.2 路由系统中的所有权限name的集合
    router_name_set = set(router_dict.keys())

    # 需要新建：数据库无、路由有
    if not generate_formset:
        generate_name_list = router_name_set - permission_name_set
        generate_formset = MultiPermissionFormSet(
            initial=[row for name, row in router_dict.items() if name in generate_name_list])

    # 需要删除：数据库有、路由无
    destroy_name_list = permission_name_set - router_name_set
    destroy_formset = MultiPermissionFormSet(
        initial=[row for name, row in permisssion_dict.items() if name in destroy_name_list])

    # 需要更新：数据库有、路由有
    if not update_formset:
        update_name_list = permission_name_set.intersection(router_name_set)
        update_formset = MultiPermissionFormSet(
            initial=[row for name, row in router_dict.items() if name in update_name_list])

    return render(
        request,
        'rbac/multi_permissions.html',
        {
            'destroy_formset': destroy_formset,
            'update_formset': update_formset,
            'generate_formset': generate_formset,
        }
    )


def distribute_permissions(request):
    """
    分配权限
    :param request:
    :return:
    """
    uid = request.GET.get('uid')
    rid = request.GET.get('rid')

    from django.utils.module_loading import import_string
    from django.conf import settings
    user_class = import_string(settings.USER_MODEL_PATH)

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        # 更新选择用户所拥有的角色
        user = user_class.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        user.roles.set(request.POST.getlist('roles'))

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = models.Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permissions.set(request.POST.getlist('permissions'))

    user_list = user_class.objects.all()
    # ############################## 角色信息 ##########################
    # 当前用户拥有的角色
    user_has_roles = user_class.objects.filter(id=uid).values('id', 'roles')
    user_has_roles_dict = {item['roles']: None for item in user_has_roles}

    # 所有的角色
    role_list = models.Role.objects.all()

    # ############################## 权限信息 ##########################
    all_menu_list = []

    if rid:
        role_has_permissions = models.Role.objects.filter(id=rid, permissions__id__isnull=False).values('id',
                                                                                                        'permissions')
    elif uid and not rid:
        user = user_class.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        role_has_permissions = user.roles.filter(permissions__id__isnull=False).values('id', 'permissions')
    else:
        role_has_permissions = []

    role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}

    # 菜单
    queryset = models.Menu.objects.values('id', 'title')
    menu_dict = {}
    for item in queryset:
        item['children'] = []
        menu_dict[item['id']] = item
        all_menu_list.append(item)

    other = {'id': None, 'title': '其他', 'children': []}
    all_menu_list.append(other)
    menu_dict[None] = other

    # 根权限
    root_permission = models.Permission.objects.filter(menu__isnull=False).values('id', 'title', 'menu_id')
    root_permission_dict = {}
    for per in root_permission:
        per['children'] = []
        nid = per['id']
        menu_id = per['menu_id']
        # print(nid, menu_id)
        root_permission_dict[nid] = per
        menu_dict[menu_id]['children'].append(per)

    # 子权限
    node_permission = models.Permission.objects.filter(menu__isnull=True).values('id', 'title', 'parent_id')
    for per in node_permission:
        parent = per['parent_id']
        if not parent:
            menu_dict[None]['children'].append(per)
            continue
        root_permission_dict[parent]['children'].append(per)

    return render(

extra_apps/rbac/templates/rbac/breadcrumb.html
<ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
    {% for item in breadcrumb_list %}
        {% if item.class %}
            <li class="{{ item.class }}">{{ item.title }}</li>
        {% else %}
            <li><a href="{{ item.url }}">{{ item.title }}</a></li>
        {% endif %}
    {% endfor %}

</ol>

extra_apps/rbac/templates/rbac/denied.html
{% extends 'layout.html' %}
{% block content %}
<div class="jumbotron">
    <div class="container">
        <h1>Ooops, Permission Denied</h1>
        <p>{{ msg }}</p>
        <p><a class="btn btn-primary btn-lg" href="{{ redirect }}" role="button">返回</a></p>
    </div>
</div>
{% endblock %}

extra_apps/rbac/templates/rbac/menu.html
<div class="multi-menu">
    <div class="item">
        {% for item in menu_dict.values %}
            <div class="title"><span class="icon-wrap"><i class="fa {{ item.icon }}"></i></span>  {{ item.title }}</div>
            <div class="body {{ item.class }}">
                {% for per in item.children %}
                    <a href="{{ per.url }}" class="{{ per.class }}">{{ per.title }}</a>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>

extra_apps/rbac/templates/rbac/menu_change.html
{% extends 'layout.html' %}
{% load rbac %}


{% block css %}
    <style>
        .icon-area ul {
            list-style-type: none;
            padding: 0;
        }

        .icon-area ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .icon-area ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }


    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">菜单名称：</label>
                <div class="col-sm-6">
                    {{ form.title }}

                </div>
                <div class="col-sm-offset-1 col-sm-2">
                    <input type="submit" value="保 存" class="btn btn-primary">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">图标：</label>
                <div class="col-sm-7 icon-area">
                    {{ form.icon }}
                </div>
                <div class="col-sm-3">
                    <div>{{ form.title.errors.0 }}</div>
                    <div>{{ form.icon.errors.0 }}</div>
                </div>
            </div>

        </form>
    </div>


{% endblock %}

{% block js %}
{% endblock %}

extra_apps/rbac/templates/rbac/menu_list.html
{% extends 'layout.html' %}

{% block css %}
    <style>

        .menu-area tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }

        #menuBody td[mid], #permissionBody > .root .title {
            cursor: pointer;
        }

        #permissionBody tr.root {
            background-color: #f1f7fd;
        }

        td a {
            margin: 0 2px;
            cursor: pointer;
        }

        table {
            font-size: 12px;
        }

        .panel-body {
            font-size: 12px;
        }

        .panel-body .form-control {
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <div class="col-md-3 menu-area">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-book" aria-hidden="true"></i> 菜单管理
                    <a href="{% url 'rbac:menu_add' %}" class="right btn btn-success btn-xs"
                       style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        新建
                    </a>
                </div>
                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>图标</th>
                        <th>选项</th>
                    </tr>
                    </thead>
                    <tbody id="menuBody">
                    {% for item in menu_list %}
                        {% if item.id|safe == mid %}
                            <tr class="active">
                                {% else %}
                            <tr>
                        {% endif %}
                    <td><a href="?mid={{ item.id }}"
                           style="display: block">{{ item.title }}（{{ item.permission_set.count }}）</a></td>
                    <td><i class="fa {{ item.icon }}" aria-hidden="true"></i></td>
                    <td>
                        <a href="{% url 'rbac:menu_edit' pk=item.id %}" style="color: #333333;">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        <a href="{% url 'rbac:menu_del' pk=item.id %}" style="color: #d9534f;">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </a>
                    </td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-cubes" aria-hidden="true"></i>权限管理
                    <div class="btn-group right">
                        <a href="{% url 'rbac:permission_add' %}" class="btn btn-xs btn-success"
                           style="padding: 2px 8px;margin: -3px;">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                            新建
                        </a>
                        <a href="{% url 'rbac:multi_permissions' %}" class="btn btn-xs btn-primary"
                           style="padding: 2px 8px;margin: -3px;">
                            <i class="fa fa-mail-forward" aria-hidden="true"></i>
                            批量操作
                        </a>
                    </div>
                </div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>URL</th>
                        <th>CODE</th>
                        <th>菜单</th>
                        <th>所属菜单</th>
                        <th>选项</th>
                    </tr>
                    </thead>
                    <tbody id="permissionBody">
                    {% for root in root_permission_list %}
                        <tr class="root" id="{{ root.id }}">
                            <td class="title">
                                <i class="fa fa-caret-down" aria-hidden="true"></i>
                                {{ root.title }}</td>
                            <td>{{ root.url }}</td>
                            <td>{{ root.name }}</td>
                            {% if root.menu__title %}
                                <td>是</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                            <td>
                                {% if root.menu__title %}
                                    {{ root.menu__title }}
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'rbac:permission_edit' pk=root.id %}" style="color:#333333;">
                                    <i class="fa fa-edit" aria-hidden="true"></i></a>
                                <a href="{% url 'rbac:permission_del' pk=root.id %}" style="color:#d9534f;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                        {% for child in root.children %}
                            <tr class="node" pid="{{ root.id }}">
                                <td class="title">{{ child.title }}</td>
                                <td>{{ child.url }}</td>
                                <td>{{ child.name }}</td>
                                <td></td>
                                <td>{{ child.menu__title }}</td>
                                <td>
                                    <a href="{% url 'rbac:permission_edit' pk=root.id %}" style="color:#333333;">
                                        <i class="fa fa-edit" aria-hidden="true"></i></a>
                                    <a href="{% url 'rbac:permission_del' pk=root.id %}" style="color:#d9534f;">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="menuDelete" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <p>One fine body&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

{% endblock %}

{% block js %}
    <script>
        $(function () {
            bindRootPermissionClick();
        });

        function bindRootPermissionClick() {
            $('#permissionBody').on('click', '.root .title', function () {
                var caret = $(this).find('i');
                var id = $(this).parent().attr('id');
                if (caret.hasClass('fa-caret-right')) {
                    caret.removeClass('fa-caret-right').addClass('fa-caret-down');
                    $(this).parent().nextAll('tr[pid="' + id + '"]').removeClass('hide');
                } else {
                    caret.removeClass('fa-caret-down').addClass('fa-caret-right');
                    $(this).parent().nextAll('tr[pid="' + id + '"]').addClass('hide');

                }
            })
        }


    </script>
{% endblock %}

extra_apps/rbac/templates/rbac/permission_change.html
{% extends 'layout.html' %}
{% load rbac %}


{% block css %}
    <style>
        .icon-area ul {
            list-style-type: none;
            padding: 0;
        }

        .icon-area ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .icon-area ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }


    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}

            {% for item in form %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ item.label }}</label>
                    <div class="col-sm-6">
                        {{ item }}
                        {{ item.errors.0 }}
                    </div>
                    <div class="col-sm-4 control-label" style="text-align: left;">
                        <label style="color: #9d9d9d;font-weight: normal;">{{ item.help_text }}</label>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                    <input type="submit" value="提交" class="btn btn-primary">
                </div>
            </div>

        </form>
    </div>


{% endblock %}

{% block js %}
{% endblock %}

extra_apps/rbac/templates/rbac/role_change.html
{% extends 'layout.html' %}
{% load rbac %}


{% block css %}
    <style>
        .icon-area ul {
            list-style-type: none;
            padding: 0;
        }

        .icon-area ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .icon-area ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }


    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">角色名称：</label>
                <div class="col-sm-3">
                    {{ form.title }}
                </div>
                <label class="col-sm-2 control-label">唯一标识：</label>
                <div class="col-sm-3">
                    {{ form.code }}
                </div>
                <div class="col-sm-2">
                    <input type="submit" value="保 存" class="btn btn-primary">
                </div>
            </div>

        </form>
    </div>


{% endblock %}

{% block js %}
{% endblock %}

extra_apps/rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}
{% load rbac %}


{% block css %}

{% endblock %}

{% block content %}
    <div class="luffy-container">
        <div class="panel panel-default">
            <!-- Default panel contents -->

            <div class="panel-body">
                <form method="post" class="form-inline">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.title }}
                        {{ form.title.errors.0 }}
                    </div>
                    <div class="form-group">
                        {{ form.code }}
                        {{ form.code.errors.0 }}
                    </div>
                    <button type="submit" class="btn btn-success"> <i class="fa fa-plus"></i> 添 加</button>
                </form>
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>角色名称</th>
                    <th>角色标识</th>
                    <th>成员数量</th>
                    <th>权限数量</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>
                {% for item in roles %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.title }}</td>
                        <td>{{ item.code }}</td>
                        <td>{{ item.userinfo_set.count }}</td>
                        <td>{{ item.permissions.count }}</td>
                        <td style="width: 20%;">
                            <a href="{% url 'rbac:role_edit' pk=item.id %}" class="btn btn-default">
                                <i class="fa fa-edit" aria-hidden="true"></i> 编辑
                            </a>

                            <a href="{% url 'rbac:role_del' pk=item.id %}" class="btn btn-default">
                                <i class="fa fa-trash-o" aria-hidden="true"></i> 删除
                            </a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block js %}
{% endblock %}