apps/home/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# _AUTHOR_  : zhujingxiu
# _DATE_    : 2018/11/2

from django.urls import path, re_path
from home.views import my
app_name = 'home'
urlpatterns = [
    path('profile/', my.ProfileView.as_view(), name='my_profile'),
    path('password/', my.PasswordView.as_view(), name='my_password'),
    path('avatar/', my.AvatarView.as_view(), name='my_avatar'),
    re_path('homework/', my.HomeworkView.as_view(), name='my_homework'),
    re_path('homework/(?P<pk>\d+)/', my.ProfileView.as_view(), name='my_homework_detail'),
]

luffy_crm/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from xstark.sites import site
from system import views as system_view
from home.views import auth, home

urlpatterns = [
    path('admin/', admin.site.urls),

    path('rbac/', include('rbac.urls', namespace='rbac')),

    path('xstark/', site.urls),
    path('xstark/login/', system_view.login),
    path('xstark/logout/', system_view.logout),
    path('xstark/profile/', system_view.profile),
    path('xstark/dashboard/', system_view.dashboard),

    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('home/', home.IndexView.as_view(), name='index'),
    path('my/', include('home.urls', namespace='home')),
]

apps/home/views/home.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# _AUTHOR_  : zhujingxiu
# _DATE_    : 2018/11/2
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, Http404
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from system.models import College, ClassInfo, Course


class IndexView(View):

    def get(self, request):

        classes = ClassInfo.objects.all().order_by('-openday')[:10]
        colleges = College.objects.all()
        return render(request, 'index.html', {'classes': classes, 'colleges': colleges})

apps/home/views/my.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# _AUTHOR_  : zhujingxiu
# _DATE_    : 2018/11/2
from django.shortcuts import render, reverse
from django.views import View
from service.models import StudyRecord


class ProfileView(View):

    def get(self, request):

        return render(request, 'my/profile.html', {})


class PasswordView(View):

    def get(self, request):
        return render(request, 'my/profile.html', {})


class AvatarView(View):

    def get(self, request):
        return render(request, 'my/profile.html', {})


class HomeworkView(View):

    def get(self, request):
        student = request.session.get('student_info')

        records = StudyRecord.objects.filter(student__pk=student.get('id'))
        print(records)
        return render(request, 'my/homework.html', {'records': records})

apps/home/templates/common/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}base{% endblock %}  - 路飞学城</title>
    <link rel="icon" href="data:image/ico;base64,aWNv">
    <!-- Bootstrap -->
    <link href="{% static 'lib/bootstrap3/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/docs.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'lib/layer/skin/layer.css' %}">

    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'lib/bootstrap3/js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include 'common/nav.html' %}
    <div class="bs-docs-header">
        <div class="container">
            <h3>骑士计划</h3>
            <p>挖出一条进入互联网名企的新通道</p>
        </div>
    </div>
    {% block content %}{% endblock %}
    <script type="text/javascript" src="{% static 'lib/layer/layer.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

apps/home/templates/common/nav.html
<header class="navbar navbar-static-top bs-docs-nav" id="top">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar"
                    aria-controls="bs-navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'index' %}" class="navbar-brand">路飞学城</a>
        </div>
        <nav id="bs-navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'index'  %}">首页</a>
                </li>

                <li>
                    <a href="../css/">联系</a>
                </li>
                {% if student.customer.name %}
                <li>
                    <a href="{% url 'home:my_homework' %}">我的成绩</a>
                </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if student.customer.name %}
                    <li><a href="{% url 'home:my_profile' %}">{{ student.customer.name }}</a></li>
                    <li><a href="{% url 'logout' %}">注销登录</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

apps/home/templates/common/sidebar.html
{% load staticfiles %}

<div class="thumbnail">
    <img src="{% static 'image/luffy.png' %}" alt="路飞学城">
    <div class="caption">
        <h3>路飞学城</h3>
        <p>帮助有志向的年轻人通过努力学习，获得体面的工作和生活</p>
        <p><a href="https://www.luffycity.com/" class="btn btn-primary" target="_blank">传送门</a></p>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">分类</div>
    <div class="panel-body">
        Panel content
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">标签</div>
    <div class="panel-body">
        Panel content
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">归档</div>
    <div class="panel-body">
        Panel content
    </div>
</div>